-- ============================================================
-- Fraud Detection Pipeline — Database Schema
-- Database: frauddb
-- ============================================================

\c frauddb;

-- Grant schema permissions
GRANT ALL ON SCHEMA public TO appuser;

-- ─────────────────────────────────────────────────────────────
-- RAW TRANSACTIONS (all ingested records from Kafka)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS transactions_raw (
    transaction_id      VARCHAR(64)     PRIMARY KEY,
    user_id             VARCHAR(32)     NOT NULL,
    event_timestamp     TIMESTAMP       NOT NULL,
    merchant_category   VARCHAR(64)     NOT NULL,
    amount              NUMERIC(12, 2)  NOT NULL,
    location            VARCHAR(128)    NOT NULL,
    currency            VARCHAR(8)      NOT NULL DEFAULT 'USD',
    ingested_at         TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_txn_raw_user_time
    ON transactions_raw (user_id, event_timestamp);

CREATE INDEX IF NOT EXISTS idx_txn_raw_ingested
    ON transactions_raw (ingested_at);

-- ─────────────────────────────────────────────────────────────
-- FRAUD ALERTS (flagged by Spark Streaming — speed layer)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS fraud_alerts (
    alert_id            SERIAL          PRIMARY KEY,
    transaction_id      VARCHAR(64)     NOT NULL,
    user_id             VARCHAR(32)     NOT NULL,
    fraud_reason        VARCHAR(32)     NOT NULL,  -- IMPOSSIBLE_TRAVEL | HIGH_VALUE
    amount              NUMERIC(12, 2)  NOT NULL,
    location            VARCHAR(128)    NOT NULL,
    merchant_category   VARCHAR(64)     NOT NULL,
    event_timestamp     TIMESTAMP       NOT NULL,
    detected_at         TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_fraud_user
    ON fraud_alerts (user_id);

CREATE INDEX IF NOT EXISTS idx_fraud_reason
    ON fraud_alerts (fraud_reason);

CREATE INDEX IF NOT EXISTS idx_fraud_category
    ON fraud_alerts (merchant_category);

CREATE INDEX IF NOT EXISTS idx_fraud_detected
    ON fraud_alerts (detected_at);

-- ─────────────────────────────────────────────────────────────
-- VALIDATED TRANSACTIONS (non-fraud, written by Spark + Airflow ETL)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS validated_transactions (
    transaction_id      VARCHAR(64)     PRIMARY KEY,
    user_id             VARCHAR(32)     NOT NULL,
    event_timestamp     TIMESTAMP       NOT NULL,
    merchant_category   VARCHAR(64)     NOT NULL,
    amount              NUMERIC(12, 2)  NOT NULL,
    location            VARCHAR(128)    NOT NULL,
    currency            VARCHAR(8)      NOT NULL DEFAULT 'USD',
    batch_processed_at  TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_valid_user
    ON validated_transactions (user_id);

CREATE INDEX IF NOT EXISTS idx_valid_event_time
    ON validated_transactions (event_timestamp);

-- ─────────────────────────────────────────────────────────────
-- RECONCILIATION REPORTS (generated by Airflow every 6 hours)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS reconciliation_reports (
    report_id               SERIAL          PRIMARY KEY,
    window_start            TIMESTAMP       NOT NULL,
    window_end              TIMESTAMP       NOT NULL,
    total_ingress_count     INTEGER         NOT NULL DEFAULT 0,
    total_ingress_amount    NUMERIC(14, 2)  NOT NULL DEFAULT 0,
    fraud_count             INTEGER         NOT NULL DEFAULT 0,
    fraud_amount            NUMERIC(14, 2)  NOT NULL DEFAULT 0,
    validated_count         INTEGER         NOT NULL DEFAULT 0,
    validated_amount        NUMERIC(14, 2)  NOT NULL DEFAULT 0,
    generated_at            TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────
-- VIEW: fraud attempts by merchant category (for analytical report)
-- ─────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW fraud_by_category AS
SELECT
    merchant_category,
    fraud_reason,
    COUNT(*)                AS attempt_count,
    SUM(amount)             AS total_amount,
    AVG(amount)             AS avg_amount,
    MAX(amount)             AS max_amount,
    MIN(detected_at)        AS first_detected,
    MAX(detected_at)        AS last_detected
FROM fraud_alerts
GROUP BY merchant_category, fraud_reason
ORDER BY attempt_count DESC;

-- ─────────────────────────────────────────────────────────────
-- VIEW: reconciliation summary for reporting
-- ─────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW reconciliation_summary AS
SELECT
    report_id,
    window_start,
    window_end,
    total_ingress_count,
    total_ingress_amount,
    fraud_count,
    fraud_amount,
    validated_count,
    validated_amount,
    ROUND(
        CASE WHEN total_ingress_amount > 0
             THEN (fraud_amount / total_ingress_amount) * 100
             ELSE 0
        END, 2
    ) AS fraud_percentage,
    generated_at
FROM reconciliation_reports
ORDER BY generated_at DESC;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO appuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO appuser;

\echo 'Schema initialized successfully.'
